---
title: "The Chamber of Labour elections | AK Wahl"
navbar: false
execute:
  echo: false 
  warning: false
subtitle: ""
fig-responsive: false
format:
  html:
    page-layout: article 
editor_options: 
  chunk_output_type: console
---

```{=html}
<span style="font-size:0.9em;">Author: <a href="https://www.linkedin.com/in/itishchenko/">Ilya Tishchenko</a></span><br><br>
```
Austria has 26% of employee in trade union, this is 33rd place in the world, however there is organisation in Austria where all workers are members, even non-citizens like me and I become curious.

```{=html}
<iframe title="Trade Union Density" aria-label="Table" id="datawrapper-chart-m3Nwc" src="https://datawrapper.dwcdn.net/m3Nwc/1/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="927" data-external="1"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r=0;r<e.length;r++)if(e[r].contentWindow===a.source){var i=a.data["datawrapper-height"][t]+"px";e[r].style.height=i}}}))}();
</script>
```
The [Chamber of Labour](https://en.wikipedia.org/wiki/Chamber_for_Workers_and_Employees) (also known as AK, abbreviation for [Arbeiterkammer](https://www.arbeiterkammer.at/ueberuns/akerklaertsich/eng/17-Antworten.html)) represents workers in Austria, membership is compulsory. It is quite a unique organisation without the analogs in other European countries, according to [Oberhuber et.al., 2014](https://www.ssoar.info/ssoar/bitstream/document/51973/1/ssoar-sws-2014-4-oberhuber_et_al-Arbeiterkammerwahlen_in_Osterreich_1949-2014.pdf). Despite the fact that membership is mandatory there are elections to assembly and in 2024 there is elections in AK. Those happening in [various dates in various regions](https://www.arbeiterkammer.at/wahl), for instance in [Tirol](https://tirol.orf.at/stories/3244240/) and [Voralberg](https://vorarlberg.orf.at/stories/3244263/) they are already over. And that is a rare occasion where I, as non-citizen, can vote, so I become curious.

I've took and cleaned up [the data](https://www.arbeiterkammer.at/ueberuns/akwahl/AK_Wahlen_1949-2019.pdf "pdf") and build a few graphs to answer the questions that arise in my head. How in general is turnout? Below I compare it to turnout on parliament elections, the latter is quite impressive on it's own.

As [Oberhuber et. al., 2014](https://www.ssoar.info/ssoar/handle/document/51973) mention this kind of *second order elections,* which didn't form the government, are in general has lower turnout so no surprise it has lower turnout.

```{=html}
<iframe title="Turnout" aria-label="Grouped Columns" id="datawrapper-chart-bYhOq" src="https://datawrapper.dwcdn.net/bYhOq/1/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="575" data-external="1"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r=0;r<e.length;r++)if(e[r].contentWindow===a.source){var i=a.data["datawrapper-height"][t]+"px";e[r].style.height=i}}}))}();
</script>
```
Plus some changes in labor market structure and lows affects it. One could see a significant drop in turnout in 1994, it has a lot to do with an increase of vote base by 31%[^1]

[^1]: Electoral law reform from 1992 included unemployed, women on maternity leave and marginally employed people.

Without digging into the data further who do you think most common winner for such a chamber? Just pause a bit and think - I bet you thought socialist. If not please [write me why not](https://www.linkedin.com/in/itishchenko/)? It's a socialist structure by foundation, supposed to protect workers, created as a counterweight to the chambers of commerce. Yes, overall always socialists won the leadership in AK. Here comes my second question. How it correlates with parliament elections?

```{=html}
<iframe title="Comparison of parties results" aria-label="Interactive line chart" id="datawrapper-chart-tl1Cf" src="https://datawrapper.dwcdn.net/tl1Cf/1/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="509" data-external="1"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r=0;r<e.length;r++)if(e[r].contentWindow===a.source){var i=a.data["datawrapper-height"][t]+"px";e[r].style.height=i}}}))}();
</script>
```
As could be seen only socialists (SPÖ[^2]) has a gap downwards, result in parliament always lower than in AK elections. From the last elections in 2019 the gap between results in AK (60%) and parliament (21%) is the biggest. For ÖVP the gap sometimes is really small and volatile, starting from 90s. FPÖ gap is growing lately with their increased popularity in parliament but their representation in AK remain more or less stable.

[^2]: I'll call it SPÖ for simplicity, though in AK elections it's FSG, same applies to other major parties ÖVP, FPÖ

The open, rather ritorical question I have is if everybody vote for socialist to protect herself as an employee why people vote for other parties during parliament elections?

```{=html}
<iframe title="AK elections results in 2014" aria-label="Map" id="datawrapper-chart-q3GUV" src="https://datawrapper.dwcdn.net/q3GUV/1/" scrolling="no" frameborder="0" style="width: 0; min-width: 100% !important; border: none;" height="456" data-external="1"></iframe><script type="text/javascript">!function(){"use strict";window.addEventListener("message",(function(a){if(void 0!==a.data["datawrapper-height"]){var e=document.querySelectorAll("iframe");for(var t in a.data["datawrapper-height"])for(var r=0;r<e.length;r++)if(e[r].contentWindow===a.source){var i=a.data["datawrapper-height"][t]+"px";e[r].style.height=i}}}))}();
</script>
```
Maps of voting are boring, so I might come up with something else or remove it completely, it's place holder for now.

Data available in repository [github.com/vearlen/ak_whal](https://github.com/vearlen/ak_wahl)
